name: ci
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    strategy:
      matrix:
        command: [
          "lint/go",
          "test/go",
        ]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Run ${{ matrix.command }}
        run: bin/builder tidy/go ${{ matrix.command }} git/isclean
